### ISSUE TITLE
Can't start after installation

### ISSUE THREAD

**Issue by dseguy** [lambdazen/bitsy#10]
I installed Bitsy on Tinkerpop 3.3.3 and Java 8.161 on OSX.

I followed the installation instruction for the gremlin-server. I changed the port to 9182 and the path for the data to an empty directory.

I get the following feedback : Apparently, the main class com.lambdazen.bitsy.BitsyGraph is not found, yet all the jar are available. 

This seems like a simple error, but I don't know where to start.

```
bin/gremlin-server.sh conf/gremlin-server-bitsy.yaml
[INFO] GremlinServer - 
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----

[INFO] GremlinServer - Configuring Gremlin Server from conf/gremlin-server-bitsy.yaml
[INFO] MetricManager - Configured Metrics Slf4jReporter configured with interval=180000ms and loggerName=org.apache.tinkerpop.gremlin.server.Settings$Slf4jReporterMetrics
[WARN] DefaultGraphManager - Graph [graph] configured at [conf/bitsy.properties] could not be instantiated and will not be available in Gremlin Server.  GraphFactory message: GraphFactory could not find [com.lambdazen.bitsy.BitsyGraph] - Ensure that the jar is in the classpath
java.lang.RuntimeException: GraphFactory could not find [com.lambdazen.bitsy.BitsyGraph] - Ensure that the jar is in the classpath
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:63)
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:104)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.lambda$new$0(DefaultGraphManager.java:57)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:55)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:80)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:120)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:84)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:343)
[INFO] ServerGremlinExecutor - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
Exception in thread "main" java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.lambdazen.bitsy.jsr223.BitsyGremlinPlugin
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.initializeGremlinScriptEngineManager(GremlinExecutor.java:448)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.<init>(GremlinExecutor.java:105)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.<init>(GremlinExecutor.java:74)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor$Builder.create(GremlinExecutor.java:590)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:128)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:120)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:84)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:343)
Caused by: java.lang.ClassNotFoundException: com.lambdazen.bitsy.jsr223.BitsyGremlinPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.initializeGremlinScriptEngineManager(GremlinExecutor.java:411)
	... 7 more
[INFO] OpLoader - Adding the standard OpProcessor.
[INFO] OpLoader - Adding the session OpProcessor.
[INFO] OpLoader - Adding the traversal OpProcessor.
[INFO] GremlinServer - Shutting down OpProcessor[]
[INFO] GremlinServer - Shutting down OpProcessor[session]
[INFO] GremlinServer - Shutting down OpProcessor[traversal]
[INFO] GremlinServer - Shutting down thread pools.
Exception in thread "gremlin-server-shutdown" java.lang.NullPointerException
	at org.apache.tinkerpop.gremlin.server.GremlinServer.stop(GremlinServer.java:253)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$new$0(GremlinServer.java:101)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dseguy** [comment]
Hi Sridhar,

I checked the following 5 JAR in the ext/bitsy/
```
bitsy-3.0.2.jar
jackson-annotations-2.9.2.jar
jackson-core-2.9.2.jar
jackson-databind-2.9.2.jar
ness-core-1.8.0.jar
```

I only use the server, not the console : I reach the server via websocket. I don't think it is important here.

I'm testing with bitsy 3.0.2, freshly downloaded. 

I untared the bitsy-3.0.2.jar, and I found the class you mentioned, in the correct folder.

**Comment by cstamas** [comment]
Isn't `ext/NAME/plugin` the correct path?

**Comment by cstamas** [comment]
I use `ext/bitsy/plugin` (and `ext/bitsy/lib` as for that matter, but as i see from `console.sh` only the former is searched by it. It works for OK.

**Comment by dseguy** [comment]
@cstamas You are right. I added an extra folder 'plugin' inside 'bitsy' and moved all the Jar there.

Then, I managed to start the gremlin-server, and make some basic queries.

Thanks :) 

May I suggest update in the docs ? 
I followed this one : https://github.com/lambdazen/bitsy/wiki
and it mentions creating ext/bitsy

**Comment by lambdazen** [comment]
Thanks @cstamas and @dseguy ! I see that the Gremlin .sh files refers to 'plugin' in a sed script -- https://github.com/apache/tinkerpop/blob/a418226574f85d3289807f8bae5d28adc2114895/gremlin-console/src/main/bin/gremlin.sh -- which isn't there in the .bat files. 

I have updated the docs. This should work on both Win & Unix. Thanks again!
