### ISSUE TITLE
Encountered exception in thread MemToTxLogWriter-1

### ISSUE THREAD

**Issue by zhuguocheng29** [lambdazen/bitsy#19]
Now I use bitsy in Android. However, it makes a mistake after running for a while.

This is the version of bitsy I use in gradle
`implementation group: 'com.lambdazen.bitsy', name: 'bitsy', version: '3.2.1'
`

This is exception log.
```
08-28 13:33:20.089 18317 18333 W System.err: com.lambdazen.bitsy.BitsyException: EXCEPTION_IN_FLUSH: The given exception occurred in the different thread while flushing a double buffer. Encountered exception in thread MemToTxLogWriter-1
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.util.DoubleBufferThread.doFlush(DoubleBufferThread.java:66)
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.util.DoubleBufferThread.run(DoubleBufferThread.java:43)
08-28 13:33:20.089 18317 18333 W System.err: Caused by: com.lambdazen.bitsy.BitsyException: EXCEPTION_IN_FLUSH: The given exception occurred in the different thread while flushing a double buffer. Encountered exception in thread TxFlusher-1
08-28 13:33:20.089 18317 18333 W System.err: 	... 2 more
08-28 13:33:20.089 18317 18333 W System.err: Caused by: com.lambdazen.bitsy.BitsyException: CHECKSUM_MISMATCH: Encountered a checksum mismatch while loading a database file. Line 6112 in file /storage/emulated/0/Android/data/com.explorer.android.testing.test/files/bitsy/txB.txt has the wrong hash-code 14fe5636. Expected 6d4a90ed
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.store.Record.parseRecord(Record.java:118)
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.store.CompactAndCopyTask.run(CompactAndCopyTask.java:71)
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore$TxLogQueuer.onQueue(FileBackedMemoryGraphStore.java:710)
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore$TxLogQueuer.onQueue(FileBackedMemoryGraphStore.java:688)
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.util.DoubleBufferWithExecWork.addAndExecuteWork(DoubleBufferWithExecWork.java:20)
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore$TxBatchFlusher.flushBuffer(FileBackedMemoryGraphStore.java:676)
08-28 13:33:20.089 18317 18333 W System.err: 	at com.lambdazen.bitsy.util.DoubleBufferThread.doFlush(DoubleBufferThread.java:64)
08-28 13:33:20.089 18317 18333 W System.err: 	... 1 more
```

This is my initialization and save data method

```
BitsyGraph graph = new BitsyGraph(dbPath);
GraphTraversalSource g = graph.traversal();
...
graph.tx().commit();
```

**Comment by zhuguocheng29** [comment]
@lambdazen 
I have a another question that why total storage size is become smaller than before even I don't remove the data. Are there some compress operation ?

```
equuleus:/storage/emulated/0/Android/data/com.explorer.android.testing.test/files/bitsy # ls -alh
total 1.5M
drwxrwx--x 2 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 .
drwxrwx--x 3 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 ..
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 eA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 468K 2019-08-28 14:31 eB.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaA.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaB.txt
-rw-rw---- 1 u0_a149 sdcard_rw 2.0M 2019-08-28 14:31 txA.txt
-rw-rw---- 1 u0_a149 sdcard_rw   14 2019-08-28 14:31 txB.txt
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 vA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 567K 2019-08-28 14:31 vB.txt
equuleus:/storage/emulated/0/Android/data/com.explorer.android.testing.test/files/bitsy # ls -alh
total 2.2M
drwxrwx--x 2 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 .
drwxrwx--x 3 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 ..
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 eA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 468K 2019-08-28 14:31 eB.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaA.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaB.txt
-rw-rw---- 1 u0_a149 sdcard_rw 3.4M 2019-08-28 14:32 txA.txt
-rw-rw---- 1 u0_a149 sdcard_rw   14 2019-08-28 14:31 txB.txt
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 vA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 567K 2019-08-28 14:31 vB.txt
equuleus:/storage/emulated/0/Android/data/com.explorer.android.testing.test/files/bitsy # ls -alh
total 882K
drwxrwx--x 2 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 .
drwxrwx--x 3 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 ..
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 eA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 632K 2019-08-28 14:32 eB.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaA.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaB.txt
-rw-rw---- 1 u0_a149 sdcard_rw   14 2019-08-28 14:32 txA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 232K 2019-08-28 14:33 txB.txt
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 vA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 836K 2019-08-28 14:32 vB.txt
equuleus:/storage/emulated/0/Android/data/com.explorer.android.testing.test/files/bitsy # ls -alh
total 922K
drwxrwx--x 2 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 .
drwxrwx--x 3 u0_a149 sdcard_rw 4.0K 2019-08-28 14:28 ..
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 eA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 632K 2019-08-28 14:32 eB.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaA.txt
-rw-rw---- 1 u0_a149 sdcard_rw   28 2019-08-28 14:28 metaB.txt
-rw-rw---- 1 u0_a149 sdcard_rw   14 2019-08-28 14:32 txA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 313K 2019-08-28 14:33 txB.txt
-rw-rw---- 1 u0_a149 sdcard_rw    0 2019-08-28 14:31 vA.txt
-rw-rw---- 1 u0_a149 sdcard_rw 836K 2019-08-28 14:32 vB.txt
```

**Comment by lambdazen** [comment]
@zhuguocheng29 

> I have a another question that why total storage size is become smaller than before even I don't remove the data. Are there some compress operation ?

Yes, there's a vertex/edge re-organization algorithm that reduces file sizes by removing duplicate updates. More info at: https://github.com/lambdazen/bitsy/wiki/WriteAlgorithms.md

> ... CHECKSUM_MISMATCH: Encountered a checksum mismatch while loading a database file. 

Can you attach the file right after the failure? For e.g., the checksum mismatch happens at "Line 6112 in file /storage/emulated/0/Android/data/com.explorer.android.testing.test/files/bitsy/txB.txt has the wrong hash-code 14fe5636. Expected 6d4a90ed" 

Having this file will help me find out what conditions cause the hash-codes to mismatch. The hash-codes are definitely "clean" in that they are 8 characters as expected. So I don't think this is related to a read/write failure. 

It's something silly like character encoding. FWIW, the hashcodes are generated in lines 81, 97, 104 and 115 (where it fails) in https://github.com/lambdazen/bitsy/blob/master/src/main/java/com/lambdazen/bitsy/store/Record.java

Regards,

Sridhar.

**Comment by lambdazen** [comment]
I think this is related to: https://stackoverflow.com/questions/25314471/string-hashcode-always-the-same-result

Since I don't have Bitsy running on Android, I'll need your help to validate the fix. Please check the 3.2.2-SNAPSHOT to see it fixes your issue: https://oss.sonatype.org/content/groups/public/com/lambdazen/bitsy/bitsy/3.2.2-SNAPSHOT/

You will have to recreate the graph from scratch because the existing hashcodes are wrong. But once you create it, you can test by restarting VM, adding a bunch of vertices, edges, etc. 

Regards,

Sridhar.

**Comment by zhuguocheng29** [comment]
@lambdazen 
I use your newest 3.2.2-SNAPSHOT, however, it still doesn't work.

the error data line is 
`V={"id":"8d4c0fcc-e547-416e-8338-9cbdbceee688","v":7,"s":"M","p":{"bounds":"[420,116][660,182]","checkable":"false","checked":"false","class":"TV","clickable":"false","content-desc":"","enabled":"true","focusable":"true","focused":"false","index":"0","kernel":"[TV|miui:id/action_bar_title]+声音与振动","long-clickable":"false","name":"声音与振动","package":"com.android.settings","password":"false","resource-id":"miui:id/action_bar_title","scrollable":"false","selected":"false","state":"106a3a3a-922b-4462-b3fb-c042d1421e45","text":"声音与振动"},"l":"Node"}#a37b93f3`

the error log is
```
2019-08-31 12:51:50.572 16875-16892/com.explorer.android.testing W/System.err: com.lambdazen.bitsy.BitsyException: EXCEPTION_IN_FLUSH: The given exception occurred in the different thread while flushing a double buffer. Encountered exception in thread MemToTxLogWriter-1
2019-08-31 12:51:50.572 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.util.DoubleBufferThread.doFlush(DoubleBufferThread.java:66)
2019-08-31 12:51:50.572 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.util.DoubleBufferThread.run(DoubleBufferThread.java:43)
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err: Caused by: com.lambdazen.bitsy.BitsyException: EXCEPTION_IN_FLUSH: The given exception occurred in the different thread while flushing a double buffer. Encountered exception in thread TxFlusher-1
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err: 	... 2 more
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err: Caused by: com.lambdazen.bitsy.BitsyException: CHECKSUM_MISMATCH: Encountered a checksum mismatch while loading a database file. Line 2490 in file /storage/emulated/0/Android/data/com.explorer.android.testing.test/files/bitsy/txB.txt has the wrong hash-code a37b93f3. Expected c782989e
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.store.Record.parseRecord(Record.java:118)
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.store.CompactAndCopyTask.run(CompactAndCopyTask.java:71)
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore$TxLogQueuer.onQueue(FileBackedMemoryGraphStore.java:710)
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore$TxLogQueuer.onQueue(FileBackedMemoryGraphStore.java:688)
2019-08-31 12:51:50.573 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.util.DoubleBufferWithExecWork.addAndExecuteWork(DoubleBufferWithExecWork.java:20)
2019-08-31 12:51:50.574 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore$TxBatchFlusher.flushBuffer(FileBackedMemoryGraphStore.java:676)
2019-08-31 12:51:50.574 16875-16892/com.explorer.android.testing W/System.err:     at com.lambdazen.bitsy.util.DoubleBufferThread.doFlush(DoubleBufferThread.java:64)
2019-08-31 12:51:50.574 16875-16892/com.explorer.android.testing W/System.err: 	... 1 more
```

**Comment by lambdazen** [comment]
Did you generate the file with the new snapshot? Also, please let me know if 

    System.getProperty("java.vendor")

Returns "The Android Project" for you. The patch uses a proprietary hashcode implementation only in this case. 

I will also test a checksum for your string on Monday and let you know what I find out. The other issue could be character encoding... It will help to know if this only occurs with Chinese characters. 

Regards,

Sridhar.

**Comment by zhuguocheng29** [comment]
@lambdazen 

Yes, I generate the file with the new snapshot and `System.getProperty("java.vendor")`
returns "The Android Project".

**Comment by lambdazen** [comment]
@zhuguocheng29 I am not able to reproduce the issue, but I have a temporary workaround where the record delimiter is always '#499602d2' for Android systems. 

Please let me know if the latest snapshot works for you.

**Comment by zhuguocheng29** [comment]
@lambdazen 

Now I have another problem when I run my project. In fact, I use the below configuration before, because 1.9.1 version of ness-core has some problem that I can't build successfully.

```
implementation group: 'com.lambdazen.bitsy', name: 'bitsy', version: '3.2.1' exclude module: 'ness-core'
implementation group: 'com.nesscomputing.components', name: 'ness-core', version: '1.9.0'
```

I import your latest snapshot like this

`implementation files('/Users/zhuguocheng/Projects/script/agent/explorer/bitsy-3.2.2-20190902.173659-2.jar')`

But I meet this problem:

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
	at com.lambdazen.bitsy.BitsyGraph.<init>(BitsyGraph.java:120)
	at com.lambdazen.bitsy.BitsyGraph.<init>(BitsyGraph.java:101)
	at com.lambdazen.bitsy.BitsyGraph.<init>(BitsyGraph.java:90)
```

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.explorer.android.testing.test-b66eKVyKg8dV0XKHSX1zLA==/base.apk", zip file "/data/app/com.explorer.android.testing-XBRglmrRaWL9uqa3jN_yVg==/base.apk"],nativeLibraryDirectories=[/data/app/com.explorer.android.testing.test-b66eKVyKg8dV0XKHSX1zLA==/lib/arm64, /data/app/com.explorer.android.testing-XBRglmrRaWL9uqa3jN_yVg==/lib/arm64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 35 more
```

**Comment by lambdazen** [comment]
@zhuguocheng29 

I am surprised we didn't run into this earlier. Apparently, Android doesn't support JMX: https://stackoverflow.com/questions/19595814/android-add-java-lang-management-api

I have removed the JMX integration (needed to avoid two instances running on the same path, and for remote management) for Android in the latest 3.2.2 snapshot at https://oss.sonatype.org/content/groups/public/com/lambdazen/bitsy/bitsy/3.2.2-SNAPSHOT/

Please let me know if you get past this issue.

Regards,

Sridhar.

**Comment by lambdazen** [comment]
@zhuguocheng29 Are you able to run Bitsy on Android now?

**Comment by zhuguocheng29** [comment]
@lambdazen  Yes, it works successful in our project. We test bitsy the last month, it works stable. Thank you very much! By the way, I am interested in bitsy, I will take a time to read the source code :)
