### ISSUE TITLE
 ERROR_WRITING_TO_TX_FILE

### ISSUE THREAD

**Issue by moyu5555** [lambdazen/bitsy#22]
com.lambdazen.bitsy.BitsyException: ERROR_WRITING_TO_TX_FILE: A fatal error occurred while writing to a transaction file. The database may need to be restarted after investigating the root cause. Could not write to CommittableFileLog(/storage/emulated/0/Android/data/com.explorer.android.testing/files/c1f7a4a3715750ccad4ee4eaf3e01baa/vB.txt)
 at com.lambdazen.bitsy.util.CommittableFileLog.append(CommittableFileLog.java:324)
 at com.lambdazen.bitsy.util.CommittableFileLog.append(CommittableFileLog.java:333)
at com.lambdazen.bitsy.store.CompactAndCopyTask.run(CompactAndCopyTask.java:125)
 at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore.(FileBackedMemoryGraphStore.java:202)
 at com.lambdazen.bitsy.BitsyGraph.(BitsyGraph.java:125)
 at com.lambdazen.bitsy.BitsyGraph.(BitsyGraph.java:92)
at com.lambdazen.bitsy.BitsyGraph.(BitsyGraph.java:103)
 at com.explorer.android.testing.btree.service.GraphDBService.(GraphDBService.java:30)
 at com.explorer.android.testing.btree.bean.Brain.(Brain.java:155)
 at com.explorer.android.testing.btree.bean.Brain.create(Brain.java:210)
 at com.explorer.android.testing.btree.Explorer.createActor(Explorer.java:59)
 at com.explorer.android.testing.UIExplorer.WeightedFSM(UIExplorer.java:53)
 at java.lang.reflect.Method.invoke(Native Method)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
 at org.junit.runners.Suite.runChild(Suite.java:128)
 at org.junit.runners.Suite.runChild(Suite.java:27)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
 at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
 at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2154)
 Caused by: java.io.IOException: No space left on device
 at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
 at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:73)
 at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
 at sun.nio.ch.IOUtil.write(IOUtil.java:65)
 at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:246)
 at com.lambdazen.bitsy.util.CommittableFileLog.append(CommittableFileLog.java:330)
 ... 38 more

**Comment by lambdazen** [comment]
I see this line in the stacktract that could be the root cause:

11:13:30 12-23 51 PE36 D: TC-10816: Caused by: java.io.IOException: No
space left on device
