### ISSUE TITLE
Exception from call site #222 bootstrap method in Android

### ISSUE THREAD

**Issue by zhuguocheng29** [lambdazen/bitsy#25]
Hi, my project want to move to Monkey project in Android, but I meet this error.  The problem is caused by the following statements in BitsyGraph.java. When I comment these statements, it success, but I don't know if there are any other bad effects. Could I comment these statements or there are any other solutions? 

```
    static {
        TraversalStrategies.GlobalCache.registerStrategies(BitsyGraph.class, TraversalStrategies.GlobalCache.getStrategies(Graph.class).clone().addStrategies(BitsyTraversalStrategy.instance()));
        TraversalStrategies.GlobalCache.registerStrategies(BitsyAutoReloadingGraph.class, TraversalStrategies.GlobalCache.getStrategies(Graph.class).clone().addStrategies(BitsyTraversalStrategy.instance()));
    }

```

```
 15874-15874/? E/AndroidRuntime: FATAL EXCEPTION: main
    PID: 15874
    java.lang.BootstrapMethodError: Exception from call site #222 bootstrap method
        at org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies.sortStrategies(TraversalStrategies.java:130)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies.addStrategies(DefaultTraversalStrategies.java:47)
        at org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies$GlobalCache.<clinit>(TraversalStrategies.java:215)
        at org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies$GlobalCache.getStrategies(TraversalStrategies.java:259)
        at com.lambdazen.bitsy.BitsyGraph.<clinit>(BitsyGraph.java:72)
        at com.android.commands.monkey.Monkey.main(Monkey.java:613)
```

**Comment by lambdazen** [comment]
I have added a try-catch block in version 3.3.1. Please let me know if you still encounter the issue.

Regards,

Sridhar.

**Comment by zhuguocheng29** [comment]
@lambdazen It is successful for me, Thank you very much!
