### ISSUE TITLE
Compat to TinkerPop server v3.4.8

### ISSUE THREAD

**Issue by deusama** [lambdazen/bitsy#30]
When I use bitsy 3.3.1 as a plugin I get the following error when starting up an empty database:

````
[INFO] FileBackedMemoryGraphStore - Starting graph FileBackedMemoryGraphStore-1(path = /tinkerpop/store)
java.lang.NoSuchMethodException: java.lang.String.<init>([C, boolean)
        at java.base/java.lang.Class.getConstructor0(Class.java:3349)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
        at com.nesscomputing.uuid.NessUUID.<clinit>(NessUUID.java:181)
        at com.lambdazen.bitsy.UUID.fromString(UUID.java:40)
        at com.lambdazen.bitsy.store.VertexBeanJson.<init>(VertexBeanJson.java:27)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1261)
        at com.lambdazen.bitsy.store.Record.deserialize(Record.java:64)
        at com.lambdazen.bitsy.store.RecordReader.next(RecordReader.java:30)
        at com.lambdazen.bitsy.store.LoadTask.run(LoadTask.java:86)
        at com.lambdazen.bitsy.store.FileBackedMemoryGraphStore.<init>(FileBackedMemoryGraphStore.java:169)
        at com.lambdazen.bitsy.BitsyGraph.<init>(BitsyGraph.java:151)
        at com.lambdazen.bitsy.BitsyGraph.<init>(BitsyGraph.java:173)
        at com.lambdazen.bitsy.BitsyGraph.open(BitsyGraph.java:208)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:77)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:69)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:103)
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.lambda$new$0(DefaultGraphManager.java:57)
        at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:55)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:80)
        at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:123)
        at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:86)
        at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:351)
````

**Comment by giovibal** [comment]
I've also this problem, is due to lack of support of NessUUID lib for java 11.

The critical part in stacktrace is this:
```
        at com.nesscomputing.uuid.NessUUID.<clinit>(NessUUID.java:181)
        at com.lambdazen.bitsy.UUID.fromString(UUID.java:40)
```

**Comment by giovibal** [comment]
It seems NessUUID component is no more mantained, and that optimization was introduced in modern JDKs.
@lambdazen what do you think if we replace NessUUID with standard UUID, and remove ness dependency ?

**Comment by giovibal** [comment]
Can you test with latest version - release-3.4.1 - and give us feedback ?

**Comment by lambdazen** [comment]
Release 3.4.2 should work with Gremlin 3.4.9
