### ISSUE TITLE
Bitsy3 in TP3 server

### ISSUE THREAD

**Issue by cstamas** [lambdazen/bitsy#7]
TP3 server is 3.3.1
Bitsy3 in server is 3.0.1

Trying to use it w/ `RemoteTraversal`:
```java
tinkerGraph.traversal().withRemote(configuration)
```
where configuration points to TP3 server to graph that is backed by Bitsy3 (MING has this set up).

Exception on client side:
```
2017-12-21 11:17:02,787 [http-worker-11] INFO  c.w.m.g.t.i.GraphIngester - TP3 Graph ingester class org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph starting processing
2017-12-21 11:17:02,834 [http-worker-11] INFO  c.w.m.g.t.i.GraphIngester - TP3 Graph ingester interface org.apache.tinkerpop.gremlin.process.remote.traversal.RemoteTraversal starting processing
2017-12-21 11:17:03,238 [http-worker-11] INFO  o.a.t.g.d.Connection - Created new connection for ws://localhost:8182/gremlin
2017-12-21 11:17:03,242 [http-worker-11] INFO  o.a.t.g.d.Connection - Created new connection for ws://localhost:8182/gremlin
2017-12-21 11:17:03,242 [http-worker-11] INFO  o.a.t.g.d.ConnectionPool - Opening connection pool on Host{address=localhost/127.0.0.1:8182, hostUri=ws://localhost:8182/gremlin} with core size of 2
2017-12-21 11:17:03,371 [http-worker-11] WARN  o.s.s.s.i.UnexpectedExceptionMapper - (ID 6f0f18ab-1bb2-49a6-aeeb-b97120739adb) Unexpected exception: java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Error during serialization: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
Serialization trace:
id (org.apache.tinkerpop.gremlin.structure.util.reference.ReferenceVertex)
java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Error during serialization: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
Serialization trace:
id (org.apache.tinkerpop.gremlin.structure.util.reference.ReferenceVertex)
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at org.apache.tinkerpop.gremlin.driver.ResultSet.one(ResultSet.java:107)
	at org.apache.tinkerpop.gremlin.driver.ResultSet$1.hasNext(ResultSet.java:159)
	at org.apache.tinkerpop.gremlin.driver.ResultSet$1.next(ResultSet.java:166)
	at org.apache.tinkerpop.gremlin.driver.ResultSet$1.next(ResultSet.java:153)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal$TraverserIterator.next(DriverRemoteTraversal.java:142)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal$TraverserIterator.next(DriverRemoteTraversal.java:127)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal.nextTraverser(DriverRemoteTraversal.java:108)
	at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.processNextStart(RemoteStep.java:80)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:200)
	at com.walmart.ming.graph.tinkerpop3.ingester.GraphIngester.findOrCreateVertex(GraphIngester.java:250)
	at com.walmart.ming.graph.tinkerpop3.ingester.GraphIngester.lambda$2(GraphIngester.java:122)
	at com.walmart.ming.ingesters.tp3remote.remote.RemoteGraphWorkExecutor.execute(RemoteGraphWorkExecutor.java:60)
	at com.walmart.ming.graph.tinkerpop3.ingester.GraphIngester.begin(GraphIngester.java:120)
	at com.walmart.ming.core.internal.DefaultConsumer$IngesterTrack.start(DefaultConsumer.java:209)
	at com.walmart.ming.core.internal.DefaultConsumer$Sink.<init>(DefaultConsumer.java:92)
	at com.walmart.ming.core.internal.DefaultConsumer.sink(DefaultConsumer.java:53)
	at com.walmart.ming.server.service.internal.graph.GraphServiceImpl.syncGraph(GraphServiceImpl.java:96)
	at com.walmart.ming.server.rest.graph.GraphSyncResource.post(GraphSyncResource.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at org.sonatype.siesta.server.internal.resteasy.ComponentContainerImpl.service(ComponentContainerImpl.java:101)
	at org.sonatype.siesta.server.SiestaServlet.service(SiestaServlet.java:138)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Error during serialization: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
Serialization trace:
id (org.apache.tinkerpop.gremlin.structure.util.reference.ReferenceVertex)
	at org.apache.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:246)
	at org.apache.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:197)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at org.apache.tinkerpop.gremlin.driver.Handler$GremlinSaslAuthenticationHandler.channelRead0(Handler.java:123)
	at org.apache.tinkerpop.gremlin.driver.Handler$GremlinSaslAuthenticationHandler.channelRead0(Handler.java:67)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at org.apache.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:91)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	... 1 common frames omitted
2017-12-21 11:17:03,375 [http-worker-11] WARN  o.s.s.s.i.UnexpectedExceptionMapper - (ID 6f0f18ab-1bb2-49a6-aeeb-b97120739adb) Response: [500] 'ERROR: (ID 6f0f18ab-1bb2-49a6-aeeb-b97120739adb) java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Error during serialization: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
Serialization trace:
id (org.apache.tinkerpop.gremlin.structure.util.reference.ReferenceVertex)'; mapped from: java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Error during serialization: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
Serialization trace:
id (org.apache.tinkerpop.gremlin.structure.util.reference.ReferenceVertex)
```

Exception on TP3 Server side
```
[tcserve@Walmac ming-gremlin-server-1.0.0-SNAPSHOT]$ ./bin/gremlin-server.sh conf/gremlin-server.yaml 
[INFO] GremlinServer - 
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----

[INFO] GremlinServer - Configuring Gremlin Server from conf/gremlin-server.yaml
[INFO] MetricManager - Configured Metrics JmxReporter configured with domain= and agentId=
[INFO] ServerGremlinExecutor - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
[INFO] MingDslGremlinPlugin - Loaded MING DSL...
[INFO] ServerGremlinExecutor - Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
[INFO] FileBackedMemoryGraphStore - Starting graph FileBackedMemoryGraphStore-1(path = data/bitsy)
[INFO] ServerGremlinExecutor - Initialized gremlin-groovy GremlinScriptEngine and registered metrics
[INFO] ServerGremlinExecutor - A MingTraversalSource is now bound to [a] with mingtraversalsource[tinkergraph[vertices:0 edges:0], standard]
[INFO] ServerGremlinExecutor - A MingTraversalSource is now bound to [b] with mingtraversalsource[bitsygraph[data/bitsy], standard]
[INFO] ServerGremlinExecutor - A MingTraversalSource is now bound to [u] with mingtraversalsource[tinkergraph[vertices:0 edges:0], standard]
[INFO] ServerGremlinExecutor - A MingTraversalSource is now bound to [e] with mingtraversalsource[tinkergraph[vertices:0 edges:0], standard]
[INFO] OpLoader - Adding the standard OpProcessor.
[INFO] OpLoader - Adding the session OpProcessor.
[INFO] OpLoader - Adding the traversal OpProcessor.
[INFO] TraversalOpProcessor - Initialized cache for TraversalOpProcessor with size 1000 and expiration time of 600000 ms
[INFO] GremlinServer - Executing start up LifeCycleHook
[INFO] Logger$info - Loading Tinkergraph from data/universe-local.graphml
[INFO] Logger$info - Loading Tinkergraph from data/app-ming.graphml
[INFO] AbstractChannelizer - Configured application/vnd.gremlin-v3.0+gryo with org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0
[INFO] AbstractChannelizer - Configured application/vnd.gremlin-v3.0+gryo-stringd with org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0
[INFO] AbstractChannelizer - Configured application/vnd.gremlin-v3.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
[INFO] AbstractChannelizer - Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
[INFO] GremlinServer$1 - Gremlin Server configured with worker thread pool of 1, gremlin pool of 8 and boss thread pool of 1.
[INFO] GremlinServer$1 - Channel started at port 8182.
[WARN] AbstractGryoMessageSerializerV3d0 - Response [ResponseMessage{requestId=c0ef5acd-7b47-4f7d-8570-d72a0070d86e, status=ResponseStatus{code=SUCCESS, message='', attributes={}}, result=ResponseResult{data=[v[216f502f-4f14-4203-8426-6af911eabc94]], meta={}}}] could not be serialized by org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0.
[WARN] AbstractOpProcessor - The result [[v[216f502f-4f14-4203-8426-6af911eabc94]]] in the request c0ef5acd-7b47-4f7d-8570-d72a0070d86e could not be serialized and returned.
org.apache.tinkerpop.gremlin.driver.ser.SerializationException: org.apache.tinkerpop.shaded.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
Serialization trace:
id (org.apache.tinkerpop.gremlin.structure.util.reference.ReferenceVertex)
	at org.apache.tinkerpop.gremlin.driver.ser.AbstractGryoMessageSerializerV3d0.serializeResponseAsBinary(AbstractGryoMessageSerializerV3d0.java:193)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.makeFrame(AbstractOpProcessor.java:266)
	at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.handleIterator(TraversalOpProcessor.java:542)
	at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.lambda$iterateBytecodeTraversal$4(TraversalOpProcessor.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.tinkerpop.shaded.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
Serialization trace:
id (org.apache.tinkerpop.gremlin.structure.util.reference.ReferenceVertex)
	at org.apache.tinkerpop.shaded.kryo.serializers.ObjectField.write(ObjectField.java:101)
	at org.apache.tinkerpop.shaded.kryo.serializers.FieldSerializer.write(FieldSerializer.java:524)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeClassAndObject(Kryo.java:625)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedKryoAdapter.writeClassAndObject(ShadedKryoAdapter.java:49)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedKryoAdapter.writeClassAndObject(ShadedKryoAdapter.java:24)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.GryoSerializersV3d0$DefaultRemoteTraverserSerializer.write(GryoSerializersV3d0.java:389)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.GryoSerializersV3d0$DefaultRemoteTraverserSerializer.write(GryoSerializersV3d0.java:386)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedSerializerAdapter.write(ShadedSerializerAdapter.java:44)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeClassAndObject(Kryo.java:625)
	at org.apache.tinkerpop.shaded.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100)
	at org.apache.tinkerpop.shaded.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeClassAndObject(Kryo.java:625)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedKryoAdapter.writeClassAndObject(ShadedKryoAdapter.java:49)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedKryoAdapter.writeClassAndObject(ShadedKryoAdapter.java:24)
	at org.apache.tinkerpop.gremlin.driver.ser.ResponseMessageGryoSerializer.write(ResponseMessageGryoSerializer.java:45)
	at org.apache.tinkerpop.gremlin.driver.ser.ResponseMessageGryoSerializer.write(ResponseMessageGryoSerializer.java:34)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedSerializerAdapter.write(ShadedSerializerAdapter.java:44)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeObject(Kryo.java:531)
	at org.apache.tinkerpop.gremlin.driver.ser.AbstractGryoMessageSerializerV3d0.serializeResponseAsBinary(AbstractGryoMessageSerializerV3d0.java:177)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Class is not registered: com.lambdazen.bitsy.UUID
Note: To register this class use: kryo.register(com.lambdazen.bitsy.UUID.class);
	at org.apache.tinkerpop.shaded.kryo.Kryo.getRegistration(Kryo.java:484)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.AbstractGryoClassResolver.writeClass(AbstractGryoClassResolver.java:110)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeClass(Kryo.java:514)
	at org.apache.tinkerpop.shaded.kryo.serializers.ObjectField.write(ObjectField.java:76)
	... 27 more
```

**Comment by cstamas** [comment]
Note: the new PR contains this change: https://github.com/lambdazen/bitsy/pull/6/files#diff-b2809fec18cf7d0b9cc9b9d2c5716fe5

But breaks the build with NPE's so will try after build cleaned up.

**Comment by lambdazen** [comment]
Hi Tamas,

I have added a couple of sections in the main Wiki page at https://github.com/lambdazen/bitsy/wiki with instructions on running Bitsy with the Gremlin Console with & without the Gremlin Server. 

Please let me know if this works for you.

Regards,

Sridhar.

**Comment by lambdazen** [comment]
Version 3.0.2 should address this issue: https://mvnrepository.com/artifact/com.lambdazen.bitsy/bitsy/3.0.2

The Wiki homepage documents how Bitsy can be launched in Gremlin Server (connect using :remote from Console) and in embedded mode within the Gremlin Console: https://github.com/lambdazen/bitsy/wiki

**Comment by cstamas** [comment]
Yup, confirmed, 3.0.2 works like a charm in TP3 Server
